force-app/main/default/objects/Idol__c/Idol__c.object-meta.xml
<CustomObject>
    <description>Used for the management of Idol Talent</description>
    <label>Idol</label>
    <nameField>
        <label>Idol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Idols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_Relations__c/Public_Relations__c.object-meta.xml
<CustomObject>
    <label>Public Relation</label>
    <nameField>
        <label>PR event name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_Relations__c/fields/Idol__c.field-meta.xml
<CustomField>
    <fullName>Idol__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Idol</label>
    <referenceTo>Idol__c</referenceTo>
    <relationshipLabel>Public Relations</relationshipLabel>
    <relationshipName>Public_Relations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/prTableControllerTest.cls
@isTest
public class prTableControllerTest {
	
    @TestSetup
    static void prTableTestData(){
        Idol__c testIdol = new Idol__c(Idol_phone__c='0000000000');
        insert testIdol;

        List<Public_Relations__c> testPRs = new List<Public_Relations__c>();
        for(integer i=0; i<400; i++){
            testPRs.add(new Public_Relations__c(Name='test'+i, Idol__r=testIdol));
        }
        insert testPRs;
    }
    
    @isTest
    static void retrievePrRecordsTest() {
        

        List<sObject> PRs = prTableController.retrievePrRecords('testIdol');
        
        
        System.assertEquals(0, PRs.size());
    }
    
}